ITEM.name = "Амиодарон"
ITEM.description = "Одноразовый шприц-инъектор, который содержит в себе инъекцию препарата «Амиодарон». Обладает противовоспалительными и болеутоляющими свойствами. Обычно применяется при спасении тяжёлых ранениях. Способ употребления: внутревенные инъекции."
ITEM.model = "models/carlsmei/escapefromtarkov/medical/sj1.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 20
ITEM.healAmount = 30
ITEM.medAttr = 0
ITEM.healRevive = true
ITEM.healReviveSeconds = 120
