------------------------------------------------------------------------
-- Garrysmod fastDL resources.lua file generated by ConfigCreator.com --
------------------------------------------------------------------------

-- Workshop Items ( 2290918731 ) --

--resource.AddWorkshop( '2290932721' ) -- cotz_general