ITEM.name = "Стандартные пищевые добавки"
ITEM.description = "Картонная коробочка, содержащая в себе, судя по инструкции взади, пластиковую ложечку и стандартную единицу пищи. Внутри лишь серая кашица, на вкус как бобы. Сплошная дрянь."
ITEM.category = "Еда"
ITEM.model = "models/biscuits_box.mdl"
ITEM.hunger = 25
ITEM.thirst = 0
ITEM.empty = false
ITEM.packaged = true
ITEM.permit = "food"