------------------------------------------------------------------------
-- Garrysmod fastDL resources.lua file generated by ConfigCreator.com --
------------------------------------------------------------------------

-- Workshop Items ( 2290918731 ) --
/*
resource.AddWorkshop( '2375197722' ) -- [TPTD] Props Pack (Defense and Barricades)
resource.AddWorkshop( '2375191747' ) -- [TPTD] Props Pack (Food and Liquids)
resource.AddWorkshop( '2375024834' ) -- [TPTD] Props Pack (Medicine and Drugs)
resource.AddWorkshop( '2375159796' ) -- [TPTD] Props Pack (Interior and Exterior)
resource.AddWorkshop( '2375216244' ) -- [TPTD] Props Pack (Other and Misc)
resource.AddWorkshop( '2428613977' ) -- [TPTD] Props Pack (Crafting and Components)
resource.AddWorkshop( '2428568315' ) -- [TPTD] Props Pack (Equipment and Personal Items)
*/
