ITEM.name = "Очищенная вода"
ITEM.description = "Вода, тщательно прокипяченная и, возможно, обработанная таблеткой для обеззараживания воды. Такую уже можно спокойно пить, не волнуясь о болях в животе и неприятном послевкусии."
ITEM.model = "models/props_junk/popcan01a.mdl"
ITEM.category = "Еда"
ITEM.skin = 1
ITEM.hunger = 0
ITEM.thirst = 25
ITEM.empty = false
ITEM.permit = "food"
ITEM.water = true